import { Ingredient } from '../../src/models/ingredients/ingredient';
import { Macro, MealType, DietType, Allergen } from '@tickt-engineering/types';
import { IngredientCategory } from '../../src/models/ingredients/ingredient-category.enum';

export const mockIngredients: Ingredient[] = [
    {
        id: 1,
        name: 'Chicken Breast',
        macro: Macro.PROTEIN,
        minQuantity: 50,
        maxQuantity: 200,
        protein: 31,
        carbs: 0,
        fat: 3.6,
        quantity: 100,
        calories: 165,
        mealTypes: [MealType.LUNCH, MealType.DINNER],
        dietTypes: [DietType.STANDARD],
        allergens: [],
        cuisine: [],
        categories: [IngredientCategory.LEAN_MEAT, IngredientCategory.POULTRY],
        cookingMethods: [],
        seasonality: [],
        flavourProfiles: [],
    },
    {
        id: 2,
        name: 'Brown Rice',
        macro: Macro.CARBS,
        minQuantity: 30,
        maxQuantity: 150,
        protein: 2.6,
        carbs: 23,
        fat: 0.9,
        quantity: 100,
        calories: 112,
        mealTypes: [MealType.LUNCH, MealType.DINNER],
        dietTypes: [DietType.STANDARD, DietType.VEGETARIAN, DietType.VEGAN],
        allergens: [],
        cuisine: [],
        categories: [IngredientCategory.WHOLE_GRAINS],
        cookingMethods: [],
        seasonality: [],
        flavourProfiles: [],
    },
    {
        id: 3,
        name: 'Avocado',
        macro: Macro.FAT,
        minQuantity: 30,
        maxQuantity: 100,
        protein: 2,
        carbs: 1.9,
        fat: 19.7,
        quantity: 100,
        calories: 160,
        mealTypes: [MealType.BREAKFAST, MealType.LUNCH, MealType.DINNER],
        dietTypes: [DietType.STANDARD, DietType.VEGETARIAN, DietType.VEGAN],
        allergens: [],
        cuisine: [],
        categories: [IngredientCategory.HEALTHY_OILS],
        cookingMethods: [],
        seasonality: [],
        flavourProfiles: [],
    },
    {
        id: 4,
        name: 'Spinach',
        macro: Macro.VEGGIE,
        minQuantity: 20,
        maxQuantity: 100,
        protein: 2.9,
        carbs: 3.6,
        fat: 0.4,
        quantity: 100,
        calories: 23,
        mealTypes: [MealType.BREAKFAST, MealType.LUNCH, MealType.DINNER],
        dietTypes: [DietType.STANDARD, DietType.VEGETARIAN, DietType.VEGAN],
        allergens: [],
        cuisine: [],
        categories: [IngredientCategory.LEAFY_GREENS, IngredientCategory.ALLIUMS],
        cookingMethods: [],
        seasonality: [],
        flavourProfiles: [],
    },
    {
        id: 5,
        name: 'Tofu',
        macro: Macro.PROTEIN,
        minQuantity: 50,
        maxQuantity: 200,
        protein: 8,
        carbs: 1.9,
        fat: 4.8,
        quantity: 100,
        calories: 76,
        mealTypes: [MealType.LUNCH, MealType.DINNER],
        dietTypes: [DietType.VEGETARIAN, DietType.VEGAN],
        allergens: [Allergen.SOY],
        cuisine: [],
        categories: [IngredientCategory.PLANT_BASED_DAIRY],
        cookingMethods: [],
        seasonality: [],
        flavourProfiles: [],
    },
    {
        id: 6,
        name: 'Beef',
        macro: Macro.PROTEIN,
        minQuantity: 50,
        maxQuantity: 200,
        protein: 26,
        carbs: 0,
        fat: 15,
        quantity: 100,
        calories: 250,
        mealTypes: [MealType.LUNCH, MealType.DINNER],
        dietTypes: [DietType.STANDARD],
        allergens: [],
        cuisine: [],
        categories: [IngredientCategory.FATTY_MEAT],
        cookingMethods: [],
        seasonality: [],
        flavourProfiles: [],
    },
    {
        id: 7,
        name: 'Salmon',
        macro: Macro.PROTEIN,
        minQuantity: 50,
        maxQuantity: 200,
        protein: 22,
        carbs: 0,
        fat: 12,
        quantity: 100,
        calories: 206,
        mealTypes: [MealType.LUNCH, MealType.DINNER],
        dietTypes: [DietType.STANDARD],
        allergens: [Allergen.FISH],
        cuisine: [],
        categories: [IngredientCategory.FISH],
        cookingMethods: [],
        seasonality: [],
        flavourProfiles: [],
    },
];
