export enum Cuisine {
    ITALIAN = 'italian',
    CHINESE = 'chinese',
    INDIAN = 'indian',
    MEXICAN = 'mexican',
    JAPANESE = 'japanese',
    MEDITERRANEAN = 'mediterranean',
    FRENCH = 'french',
    THAI = 'thai',
    GREEK = 'greek',
    SPANISH = 'spanish',
    MIDDLE_EASTERN = 'middle-eastern',
    AMERICAN = 'american',
    VIETNAMESE = 'vietnamese',
    KOREAN = 'korean',
    BRITISH = 'british',
    SOUTH_AMERICAN = 'south-american',
    INDONESIAN = 'indonesian',
    CARIBBEAN = 'caribbean',
    BRAZILIAN = 'brazilian',
    EUROPEAN = 'european',
    RUSSIAN = 'russian',
    AFRICAN = 'african',
    ASIAN = 'asian',
    CANADIAN = 'canadian',
    SCANDINAVIAN = 'scandinavian',
    OTHER = 'other'
}